// Generated by scripts/generate-protected-slugs.ts — do not edit by hand.
// Used by proxy to gate protected pages without loading page JSON at request time.

export const PROTECTED_PAGE_PATHS = new Set<string>(["work/lenero", "work/project-spinach-tiff"]);
