// Generated by scripts/generate-protected-slugs.ts — do not edit by hand.
// Used by proxy to gate /work/* without calling getPage() at request time.

export const PROTECTED_SLUGS = new Set<string>(["lenero"]);
