// Generated by scripts/generate-protected-slugs.ts — do not edit by hand.
// Used by middleware to gate /work/[slug] without calling getPage() at request time.

export const PROTECTED_SLUGS = new Set<string>([]);
