import type { PreviewSurfaceMetadata } from "@/app/dev/workbench/preview-fidelity";

export const PREVIEW_FIDELITY_INVENTORY: PreviewSurfaceMetadata[] = [
  {
    surfaceId: "layout/pages",
    status: "live",
    owner: "dev-workbench",
    rendererPath: "PageBuilderRenderer",
    fidelityModeDefault: "raw",
    supportsViewport: true,
  },
  {
    surfaceId: "layout/sections",
    status: "live",
    owner: "dev-workbench",
    rendererPath: "SectionRenderer",
    fidelityModeDefault: "raw",
    supportsViewport: true,
  },
  {
    surfaceId: "layout/columns",
    status: "live",
    owner: "dev-workbench",
    rendererPath: "SectionRenderer",
    fidelityModeDefault: "raw",
    supportsViewport: true,
  },
  {
    surfaceId: "layout/scroll",
    status: "live",
    owner: "dev-workbench",
    rendererPath: "SectionRenderer",
    fidelityModeDefault: "raw",
    supportsViewport: true,
  },
  {
    surfaceId: "layout/frames",
    status: "live",
    owner: "dev-workbench",
    rendererPath: "SectionRenderer",
    fidelityModeDefault: "raw",
    supportsViewport: true,
  },
  {
    surfaceId: "elements/heading",
    status: "live",
    owner: "dev-workbench",
    rendererPath: "ElementRenderer",
    fidelityModeDefault: "raw",
    supportsViewport: true,
  },
  {
    surfaceId: "elements/body",
    status: "live",
    owner: "dev-workbench",
    rendererPath: "ElementRenderer",
    fidelityModeDefault: "raw",
    supportsViewport: true,
  },
  {
    surfaceId: "elements/link",
    status: "live",
    owner: "dev-workbench",
    rendererPath: "ElementRenderer",
    fidelityModeDefault: "raw",
    supportsViewport: true,
  },
  {
    surfaceId: "elements/button",
    status: "live",
    owner: "dev-workbench",
    rendererPath: "ElementRenderer",
    fidelityModeDefault: "raw",
    supportsViewport: true,
  },
  {
    surfaceId: "elements/rich-text",
    status: "live",
    owner: "dev-workbench",
    rendererPath: "ElementRenderer",
    fidelityModeDefault: "raw",
    supportsViewport: true,
  },
  {
    surfaceId: "elements/image",
    status: "live",
    owner: "dev-workbench",
    rendererPath: "ElementRenderer",
    fidelityModeDefault: "raw",
    supportsViewport: true,
  },
  {
    surfaceId: "elements/video",
    status: "live",
    owner: "dev-workbench",
    rendererPath: "ElementRenderer",
    fidelityModeDefault: "raw",
    supportsViewport: true,
  },
  {
    surfaceId: "elements/video-time",
    status: "live",
    owner: "dev-workbench",
    rendererPath: "ElementRenderer",
    fidelityModeDefault: "raw",
    supportsViewport: true,
  },
  {
    surfaceId: "elements/vector",
    status: "live",
    owner: "dev-workbench",
    rendererPath: "ElementRenderer",
    fidelityModeDefault: "raw",
    supportsViewport: true,
  },
  {
    surfaceId: "elements/svg",
    status: "live",
    owner: "dev-workbench",
    rendererPath: "ElementRenderer",
    fidelityModeDefault: "raw",
    supportsViewport: true,
  },
  {
    surfaceId: "elements/input",
    status: "live",
    owner: "dev-workbench",
    rendererPath: "ElementRenderer",
    fidelityModeDefault: "raw",
    supportsViewport: true,
  },
  {
    surfaceId: "elements/range",
    status: "live",
    owner: "dev-workbench",
    rendererPath: "ElementRenderer",
    fidelityModeDefault: "raw",
    supportsViewport: true,
  },
  {
    surfaceId: "elements/spacer",
    status: "live",
    owner: "dev-workbench",
    rendererPath: "ElementRenderer",
    fidelityModeDefault: "raw",
    supportsViewport: true,
  },
  {
    surfaceId: "elements/divider",
    status: "live",
    owner: "dev-workbench",
    rendererPath: "ElementRenderer",
    fidelityModeDefault: "raw",
    supportsViewport: true,
  },
  {
    surfaceId: "elements/group",
    status: "live",
    owner: "dev-workbench",
    rendererPath: "ElementRenderer",
    fidelityModeDefault: "raw",
    supportsViewport: true,
  },
  {
    surfaceId: "elements/scroll-progress-bar",
    status: "live",
    owner: "dev-workbench",
    rendererPath: "ElementRenderer",
    fidelityModeDefault: "raw",
    supportsViewport: true,
  },
  {
    surfaceId: "elements/model-3d",
    status: "live",
    owner: "dev-workbench",
    rendererPath: "ElementRenderer",
    fidelityModeDefault: "raw",
    supportsViewport: true,
  },
  {
    surfaceId: "elements/rive",
    status: "live",
    owner: "dev-workbench",
    rendererPath: "ElementRenderer",
    fidelityModeDefault: "raw",
    supportsViewport: true,
  },
];

export const LAYOUT_PREVIEW_SURFACE_IDS = [
  "layout/pages",
  "layout/sections",
  "layout/columns",
  "layout/scroll",
  "layout/frames",
] as const;
