#!/usr/bin/env npx tsx

import * as fs from "fs";
import * as path from "path";
import { discoverAllPages } from "@pb/core";

const APP_ROOT = fs.existsSync(path.join(process.cwd(), "src/content"))
  ? process.cwd()
  : path.join(process.cwd(), "apps/web");

const OUT_PATH = path.join(APP_ROOT, "src/core/lib/protected-slugs.generated.ts");

function isPasswordProtected(contentPath: string): boolean {
  try {
    const raw = fs.readFileSync(contentPath, "utf-8");
    const data = JSON.parse(raw) as { passwordProtected?: boolean };
    return data.passwordProtected === true;
  } catch {
    return false;
  }
}

function getProtectedPagePaths(): string[] {
  const pages = discoverAllPages();
  const protectedPaths = pages
    .filter((page) => isPasswordProtected(page.contentPath))
    .map((page) => page.slugSegments.join("/"))
    .filter((slugPath) => slugPath.length > 0)
    .sort((a, b) => a.localeCompare(b));
  return protectedPaths;
}

function main(): void {
  const protectedPagePaths = getProtectedPagePaths();

  const content = `// Generated by scripts/generate-protected-slugs.ts — do not edit by hand.
// Used by proxy to gate protected pages without loading page JSON at request time.

export const PROTECTED_PAGE_PATHS = new Set<string>([${protectedPagePaths.map((s) => `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`).join(", ")}]);
`;

  fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
  fs.writeFileSync(OUT_PATH, content, "utf-8");
}

main();
