#!/usr/bin/env npx tsx

import * as fs from "fs";
import * as path from "path";
import { discoverAllPages } from "../src/page-builder/core/load/page-builder-discover-pages";

const OUT_PATH = path.join(process.cwd(), "src/core/lib/protected-slugs.generated.ts");

function isPasswordProtected(contentPath: string): boolean {
  try {
    const raw = fs.readFileSync(contentPath, "utf-8");
    const data = JSON.parse(raw) as { passwordProtected?: boolean };
    return data.passwordProtected === true;
  } catch {
    return false;
  }
}

function getProtectedWorkSlugs(): string[] {
  const pages = discoverAllPages();
  const protectedSlugs = pages
    .filter((page) => page.slugSegments[0] === "work")
    .filter((page) => isPasswordProtected(page.contentPath))
    .map((page) => page.slugSegments.slice(1).join("/"))
    .filter((slug) => slug.length > 0)
    .sort((a, b) => a.localeCompare(b));
  return protectedSlugs;
}

function main(): void {
  const protectedSlugs = getProtectedWorkSlugs();

  const content = `// Generated by scripts/generate-protected-slugs.ts — do not edit by hand.
// Used by proxy to gate /work/* without calling getPage() at request time.

export const PROTECTED_SLUGS = new Set<string>([${protectedSlugs.map((s) => `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`).join(", ")}]);
`;

  fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
  fs.writeFileSync(OUT_PATH, content, "utf-8");
}

main();
