#!/usr/bin/env npx tsx

import * as fs from "fs";
import * as path from "path";

const PAGE_DATA_DIR = path.join(process.cwd(), "src/content/pages");
const PAGE_IGNORE = new Set(["schema.example.json"]);
const OUT_PATH = path.join(process.cwd(), "src/core/lib/protected-slugs.generated.ts");

function getPageSlugs(): string[] {
  if (!fs.existsSync(PAGE_DATA_DIR)) return [];
  return fs
    .readdirSync(PAGE_DATA_DIR)
    .filter((f) => f.endsWith(".json") && !PAGE_IGNORE.has(f) && !f.endsWith("-sections.json"))
    .map((f) => f.replace(/\.json$/, ""));
}

function isPasswordProtected(slug: string): boolean {
  const pagePath = path.join(PAGE_DATA_DIR, `${slug}.json`);
  if (!fs.existsSync(pagePath)) return false;
  try {
    const raw = fs.readFileSync(pagePath, "utf-8");
    const data = JSON.parse(raw) as { passwordProtected?: boolean };
    return data.passwordProtected === true;
  } catch {
    return false;
  }
}

function main(): void {
  const slugs = getPageSlugs();
  const protectedSlugs = slugs.filter(isPasswordProtected);

  const content = `// Generated by scripts/generate-protected-slugs.ts — do not edit by hand.
// Used by middleware to gate /work/[slug] without calling getPage() at request time.

export const PROTECTED_SLUGS = new Set<string>([${protectedSlugs.map((s) => `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`).join(", ")}]);
`;

  fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
  fs.writeFileSync(OUT_PATH, content, "utf-8");
}

main();
