export const PAGE_COMPOSER_PLACEHOLDER = JSON.stringify(
  {
    slug: "example",
    title: "Example Page",
    sectionOrder: ["hero", "divider", "cards"],
    bgKey: "bg",
    definitions: {
      bg: {
        type: "backgroundVariable",
        layers: [{ fill: "rgba(8, 8, 16, 1)" }],
      },
      hero: {
        type: "contentBlock",
        id: "hero",
        width: "100%",
        paddingTop: "5rem",
        paddingBottom: "4rem",
        paddingLeft: "3rem",
        paddingRight: "3rem",
        flexDirection: "column",
        gap: "1.25rem",
        elementOrder: ["eyebrow", "heading", "body", "cta"],
        definitions: {
          eyebrow: {
            type: "elementHeading",
            level: 6,
            content: "Page Composer — live pipeline preview",
            color: "rgba(120, 180, 255, 0.75)",
            textTransform: "uppercase",
            letterSpacing: "0.1em",
          },
          heading: {
            type: "elementHeading",
            level: 1,
            content: "Build pages, see them live.",
            fontWeight: "700",
            lineHeight: "1.06",
          },
          body: {
            type: "elementBody",
            content:
              "Paste any page document — sectionOrder, definitions, bgKey — and this composer expands it through the full production pipeline. Edit the JSON on the left to see changes here.",
            color: "rgba(255,255,255,0.55)",
            maxWidth: "40rem",
          },
          cta: {
            type: "elementButton",
            label: "Try pasting your own page →",
            fill: "rgba(120, 180, 255, 0.12)",
            stroke: "rgba(120, 180, 255, 0.35)",
            color: "rgba(120, 180, 255, 1)",
            borderRadius: "0.375rem",
            paddingLeft: "1.25rem",
            paddingRight: "1.25rem",
            paddingTop: "0.625rem",
            paddingBottom: "0.625rem",
            alignSelf: "flex-start",
          },
        },
      },
      divider: {
        type: "divider",
        id: "divider",
        width: "100%",
        fill: "rgba(255,255,255,0.06)",
        height: "1px",
        marginLeft: "3rem",
        marginRight: "3rem",
      },
      cards: {
        type: "sectionColumn",
        id: "cards",
        width: "100%",
        paddingTop: "3rem",
        paddingBottom: "4rem",
        paddingLeft: "3rem",
        paddingRight: "3rem",
        gap: "1.5rem",
        columns: [
          {
            type: "contentBlock",
            id: "card-a",
            flexDirection: "column",
            gap: "0.5rem",
            fill: "rgba(255,255,255,0.04)",
            borderRadius: "0.5rem",
            border: { color: "rgba(255,255,255,0.08)", width: "1px", style: "solid" },
            paddingTop: "1.5rem",
            paddingBottom: "1.5rem",
            paddingLeft: "1.5rem",
            paddingRight: "1.5rem",
            elementOrder: ["a-label", "a-body"],
            definitions: {
              "a-label": { type: "elementHeading", level: 5, content: "Paste JSON" },
              "a-body": {
                type: "elementBody",
                content: "Write or paste any valid page document and hit Expand & Preview.",
                color: "rgba(255,255,255,0.5)",
              },
            },
          },
          {
            type: "contentBlock",
            id: "card-b",
            flexDirection: "column",
            gap: "0.5rem",
            fill: "rgba(255,255,255,0.04)",
            borderRadius: "0.5rem",
            border: { color: "rgba(255,255,255,0.08)", width: "1px", style: "solid" },
            paddingTop: "1.5rem",
            paddingBottom: "1.5rem",
            paddingLeft: "1.5rem",
            paddingRight: "1.5rem",
            elementOrder: ["b-label", "b-body"],
            definitions: {
              "b-label": { type: "elementHeading", level: 5, content: "Import by slug" },
              "b-body": {
                type: "elementBody",
                content: "Type a production slug to load it through the full server pipeline.",
                color: "rgba(255,255,255,0.5)",
              },
            },
          },
          {
            type: "contentBlock",
            id: "card-c",
            flexDirection: "column",
            gap: "0.5rem",
            fill: "rgba(255,255,255,0.04)",
            borderRadius: "0.5rem",
            border: { color: "rgba(255,255,255,0.08)", width: "1px", style: "solid" },
            paddingTop: "1.5rem",
            paddingBottom: "1.5rem",
            paddingLeft: "1.5rem",
            paddingRight: "1.5rem",
            elementOrder: ["c-label", "c-body"],
            definitions: {
              "c-label": { type: "elementHeading", level: 5, content: "Inspect output" },
              "c-body": {
                type: "elementBody",
                content:
                  "Expanded SectionBlock JSON and background definition appear in the sidebar.",
                color: "rgba(255,255,255,0.5)",
              },
            },
          },
        ],
      },
    },
  },
  null,
  2
);
